### ISSUE TITLE
Instructions in AWS Blog Post

### ISSUE THREAD

**Issue by frank-tan** [aws-samples/aws-stepfunctions-examples#1] opened 2021-03-22 05:25 UTC
I followed the link to this repo from this AWS blog post https://aws.amazon.com/blogs/compute/accelerating-workloads-using-parallelism-in-aws-step-functions/

sam build as directed in the blog post didn't work for me on Mac. I had to use `sam build --use-container` to work around the problem. Hope it might help other people following the blog post.

**Comment by JustinCallison** [comment] 2021-03-22 15:21
Thanks @frank-tan. I'm not 100% sure of the cause as this built fine on my mac. I suspect it had to do with inclusion of non-standard libraries using requirements.txt. This doesn't really need that, so I've update the app to remove them which I believe will solve the problem you reported. If you get a chance to confirm, that would be much appreciated.

**Comment by JustinCallison** [comment] 2021-03-25 13:43
I am going to close this issue, because I was able to reproduce when running this in a Cloud9 environment and confirm that my changes addressed the problem.

**Closed by JustinCallison** 2021-03-25 13:43 UTC
